### ISSUE TITLE
Clarification on the 6000% Speedup Claim Over FFmpeg

### ISSUE THREAD

**Issue by sworddish** [skeskinen/smartcut#4]
Hi,

First of all, thank you for your work on this video smart cut library. I was examining the core logic, specifically the VideoCutter class, and noticed that the library claims to be 6000% faster than FFmpeg.

From my understanding, the code utilizes the PyAV library, which is a Pythonic binding for FFmpeg's libraries. Given that both tools rely on the same underlying FFmpeg technology for decoding and encoding, I'm curious about how such a significant speedup is achieved.

Could you please provide more details or benchmarks to support the speedup claim? Clarifying this would help users like me understand the benefits of your library and ensure that the performance expectations are accurate.

**Comment by skeskinen** [comment]
Hi,
This library/tool works by skipping recoding of the video when possible. The speedup is achieved by decoding/encoding less video than ffmpeg would to achieve the same results.

The 6000% claim refers only to the demo. The conditions of the demo are shown on the video.

The exact speedup is arbitrary, because you can easily construct examples where it's much faster or slower.

In general, lots of small cuts is going to be slow. Long continuous segments are fast.
